### ISSUE TITLE
The script encountered an error and will be aborted

### ISSUE THREAD

**Issue by Snowpard** [payuru/SDK_for_mobile_OS#5]
Здравствуйте! 
При добавление продукта с русским названием выдается ошибка в webView: The script encountered an error and will be aborted. To view extended error messages, enable this feature in .settings.php

Пример: builder.addProduct("Тест", "12", "1", "", "1", "19", "", "", "");
Если будет латиница, то все ок: builder.addProduct("Test", "12", "1", "", "1", "19", "", "", "");
В чем может быть проблема?
Платформа: Android.

**Comment by Snowpard** [comment]
При вводе русских символов возвращается /?err=Invalid%20Signature

**Comment by payuru** [comment]
Добрый день!
Спасибо за информацию. Быстро мы сейчас своими силами не сможем исправить проблему.
Вы можете попробовать исправить проблему сами.
Мы принимаем запросы только в UTF-8. Для расчёта подписи должна используется длинна значений параметров. Если код возвращает длинну в символах а не в байтах для кириллицы, это приводит к проблемам с подписью запроса ( /?err=Invalid%20Signature).

**Comment by Snowpard** [comment]
Спасибо за ответ! Действительно неверно считался размер строки. В методе buildForHash (класс  LUPurchaseBuilder), вместо sb.append(value.length()) надо sb.append(value.getBytes().length)
