### ISSUE TITLE
[Android] Нет возможности добавить больше одного продукта

### ISSUE THREAD

**Issue by Snowpard** [payuru/SDK_for_mobile_OS#6]
Пример для тестового кода:
builder.addProduct("Test", "12", "1", "", "1", "19", "", "", "");
builder.addProduct("Test 2", "13", "2", "", "3", "19", "", "", "");

На форме все равно будет только первый продукт

**Comment by payuru** [comment]
Добрый день!
В данный момент у нас нет возможности оперативно проверить и испправить проблему.
Вы можете попробовать решить проблему своими силами.
Вы отправляете зарос, в котором товар описан несколькими массивами. Если вы сообщите, какой запрос вы отправили, я смогу проверить, что мы получили со своей стороны.

**Comment by Snowpard** [comment]
Спасибо за ответ! Я проанализировал код. Он заточен только под 1 продукт. У себя я сделал костылями, чтобы работало. 
1. Не правильно считается сигнатура в методе buildForHash (класс LUPurchaseBuilder). Она считается только для первого продукта в списке.
2. В методе build (класс LUPurchaseBuilder) используется TreeMap. Он не работает с дубликатами ключей. Таким образом, нет возможности сделать ORDER_PNAME[] = "Test 1" и ORDER_PNAME[] = "Test 2". Всегда будет последнее значение. Надо использовать какой-нибудь MultiMap. К тому же, сейчас все считается только для первого продукта в списке

**Comment by payuru** [comment]
Добрый день!
Возможность добавления более одного продукта для LU протокола была добавлена для новой версии SDK [ссылка](https://github.com/payuru/ANDROID_SDK_PAYU).
Спасибо!
